name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    - name:  Build with Gradle
      run: ./gradlew build
      
    # Execute unit tests
   # - name: Unit Test
   #   run: ./gradlew testDebugUnitTest

    #- name: Android Test Report
     # uses: asadmansr/android-test-report-action@v1.2.0
#      if: ${{ always() }}
